[package]
name = "go-mainboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
go-module = { version = "0.1", path = "../go-module"}
embedded-hal = "1"

[features]

default = ["std"]
std = []
