[package]
name = "go-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1"

[dev-dependencies]
linux-embedded-hal = "0.4"